services:
  - type: web
    name: Professional Extractor
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python run.py"
    envVars:
      - key: FLASK_ENV
        value: production
    plan: free
